# Generated by Django 3.1.6 on 2021-02-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210217_0014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
